services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SELENIUM_DRIVER_URL: ${SELENIUM_DRIVER_URL}
      SENTRY_DSN: ${SENTRY_DSN}
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: camp_bath_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chrome:
    image: seleniarm/standalone-chromium:latest
    ports:
      - "4444:4444"

volumes:
  postgres_data:
  bundle_data: